print("CREATING ZERO DIMENSIONAL ARRAY")
import numpy as np
x=np.array(21)
print("x :",x)
print("the type of x : ",type(x))
print("the dimension of x : ",np.ndim(x))

print("ONE DIMENSIONAL ARRAY")
A=np.array([1,2,3])
B=np.array([4,5,6])
print("A : ",A)
print("B : ",B)
print("type of A:",A.dtype)
print("type of B:",B.dtype)
print("dimension of A:",np.ndim(A))
print("dimension of B:",np.ndim(B))

print("TWO DIMENSIONAL ARRAY")
C=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)
print(C.ndim)